name: artifact

on: push

jobs:
  artifact:
    runs-on: ubuntu-latest
    env: 
      ARTIFACT_NAME: "MyArtifact"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./myartifact
            


