name: test github action count files

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  check_number_of_files:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: run find
      run: find ./
    - name: test gh action
      uses: omagdy7/count_files@master
      with:
        path: "./"
